### ISSUE TITLE
Suggestion on code optimization

### ISSUE THREAD

**Issue by erosman** [richardsondev/simple-twitch-auto-bonus#1]
https://github.com/richardsondev/simple-twitch-auto-bonus/blob/e9c5199e8ead735ceeed68bf541e6a0224c2e113/src/autobonus.js#L1

`document.querySelectorAll("[class*=ScCoreButtonSuccess]")[0]` means:
- Search every element from the start to the end of the document
- Choose only the first one

Problems are that:
- `[0]` causes error if the element is not found
- Once the first one is found, the process continues until the end of the document needlessly
- There is also an issue with quotes in `("[class*=ScCoreButtonSuccess]")`

There is `querySelector()` which does the job efficiently since it will look for the fist one and then stops

Therefore ....
```js
setInterval(function(){ let x = document.querySelector('[class*="ScCoreButtonSuccess"]'); if (x != undefined) x.click(); }, 3000);
```

This is the same code, written slightly differently.
- `const` is better than `let` here
- The use of `!==` is encouraged

```js
setInterval(function(){ const x = document.querySelector('[class*="ScCoreButtonSuccess"]'); if (x !== undefined) x.click(); }, 3000);
```

This is still the same code, written slightly differently.

```js
setInterval(() => { const x = document.querySelector('[class*="ScCoreButtonSuccess"]'); x &&  x.click(); }, 3000);
```

**Comment by richardsondev** [comment]
Thanks a lot erosman! I just use this extension on my local machine and haven't really tested the performance for this for a broad audience like I should. I will investigate this for sure!

**Comment by richardsondev** [comment]
Thank you @erosman! I have uptaken the code you have suggested and submitted the extension with the updated code. It works well. I really appreciate you reaching out and sharing your knowledge.
Thank you again!
Billy
